# Generated by Django 3.0.5 on 2020-04-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Short name for the user to identify the ingredient."
                    ),
                ),
                (
                    "unit",
                    models.TextField(help_text="Unit of measure for the ingredient."),
                ),
            ],
        ),
    ]
